Feature/modal edit
iotruck/bino-portal pull request #2
Opened 2021-05-08 01:09 UTC by jose-lucas-mq

2021-05-08 01:48 UTC, jorge-lsb commented on portal/src/components/CardTravel.jsx
> +          <label htmlFor="driver" id="driver"> Motorista <i class="fas fa-plus"></i> </label>
![image](https://user-images.githubusercontent.com/61752234/117521825-40a58580-af86-11eb-982a-b8e0ee12ceac.png)

Ajuste no modal de editar infos da viagem 

um input quebra o texto e o icon

2021-05-08 01:49 UTC, jorge-lsb requested changes
Ajustar o componente de modal da CardTravel

2021-05-10 22:28 UTC, jorge-lsb approved these changes

2021-05-10 22:29 UTC, GabrielCarrera approved these changes
Bacana

2021-05-10 22:30 UTC, igor-ferreira-bezerra approved these changes

2021-05-10 22:31 UTC, merged